### ISSUE TITLE
Check friends when recovering account

### ISSUE THREAD

**Issue by cwhinfrey** [netgum/archanova-contracts#23]
I believe you want to check that a friend address passed into `recoverAccount` is in fact a friend of the account right after [this line](https://github.com/netgum/archanova-contracts/blob/develop/contracts/account/AccountFriendRecovery.sol#L116). Also, you'll want to check that there are no duplicates in the `_friends` array.

**Comment by stanislaw-glogowski** [comment]
@cwhinfrey thx, I'll fix it next release
